name: profile_image_widget
description: "A simple profile image widget for Flutter."
version: 0.0.1
repository: https://github.com/kullaniciadi/profile_image_widget
homepage: https://github.com/kullaniciadi/profile_image_widget

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
